# Generated by Django 4.1.3 on 2022-12-22 11:11

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_bio_user_name_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='cep',
            field=localflavor.br.models.BRPostalCodeField(blank='True', max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='user',
            name='state',
            field=localflavor.br.models.BRStateField(blank='True', max_length=2, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=localflavor.br.models.BRCPFField(blank='True', max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
