# Generated by Django 4.1.3 on 2022-12-22 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='complement',
        ),
    ]
