# Generated by Django 4.1.3 on 2022-12-22 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_user_complement'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='complement',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
