# Generated by Django 4.1.3 on 2022-12-22 18:16

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_procfile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='cep',
            field=localflavor.br.models.BRPostalCodeField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='complement',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='procfile_photo',
            field=models.ImageField(upload_to='procfile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=localflavor.br.models.BRStateField(max_length=2, verbose_name='State'),
        ),
    ]
