# Generated by Django 4.1.3 on 2022-12-22 18:59

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_address_alter_user_cep_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='cep',
            field=models.IntegerField(blank=True, max_length=8, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='complement',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.IntegerField(blank=True, max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='procfile_photo',
            field=models.ImageField(blank=True, upload_to='procfile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=localflavor.br.models.BRStateField(blank=True, max_length=2, verbose_name='State'),
        ),
    ]
