# Generated by Django 4.1.3 on 2022-12-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_address_alter_user_cep_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='complement',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
