# Generated by Django 4.1.3 on 2022-12-27 00:17

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_user_complement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cep',
            field=localflavor.br.models.BRPostalCodeField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF'),
        ),
    ]
