# Generated by Django 4.1.3 on 2022-12-09 22:34

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EditPageFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('slide_0_title', models.CharField(max_length=12)),
                ('slide_1_title', models.CharField(max_length=12)),
                ('slide_2_title', models.CharField(max_length=12)),
                ('slide_0_text', models.CharField(max_length=60)),
                ('slide_1_text', models.CharField(max_length=60)),
                ('slide_2_text', models.CharField(max_length=60)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
