# Generated by Django 4.1.3 on 2022-12-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_homepageslideshow_instagramsection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instagramsection',
            name='instagram_0_post',
        ),
        migrations.RemoveField(
            model_name='instagramsection',
            name='instagram_1_post',
        ),
        migrations.RemoveField(
            model_name='instagramsection',
            name='instagram_2_post',
        ),
        migrations.RemoveField(
            model_name='instagramsection',
            name='instagram_3_post',
        ),
        migrations.RemoveField(
            model_name='instagramsection',
            name='instagram_4_post',
        ),
        migrations.AddField(
            model_name='instagramsection',
            name='instagram_0_image',
            field=models.ImageField(blank=True, default='no_image', upload_to='instagram/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='instagramsection',
            name='instagram_1_image',
            field=models.ImageField(blank=True, default='no_image', upload_to='instagram/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='instagramsection',
            name='instagram_2_image',
            field=models.ImageField(blank=True, default='no_image', upload_to='instagram/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='instagramsection',
            name='instagram_3_image',
            field=models.ImageField(blank=True, default='no_image', upload_to='instagram/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='instagramsection',
            name='instagram_4_image',
            field=models.ImageField(blank=True, default='no_image', upload_to='instagram/%Y/%m/%d'),
        ),
    ]
