# Generated by Django 4.1.3 on 2022-12-10 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_instagramsection_instagram_0_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagramsection',
            name='instagram_1_text',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='instagramsection',
            name='instagram_2_text',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='instagramsection',
            name='instagram_3_text',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='instagramsection',
            name='instagram_4_text',
            field=models.TextField(default=0),
        ),
    ]
