# Generated by Django 4.1.3 on 2022-12-10 00:57

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_instagramsection_instagram_1_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('about', models.TextField()),
                ('image', models.ImageField(blank=True, default='no_image', upload_to='about/%Y/%m/%d')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='instagramsection',
            name='instagram_0_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instagramsection',
            name='instagram_1_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instagramsection',
            name='instagram_2_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instagramsection',
            name='instagram_3_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='instagramsection',
            name='instagram_4_text',
            field=models.TextField(),
        ),
    ]
