# Generated by Django 4.1.3 on 2022-12-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_aboutpage_alter_instagramsection_instagram_0_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='image',
            field=models.ImageField(upload_to='about/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='instagramsection',
            name='instagram_0_image',
            field=models.ImageField(upload_to='instagram/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='instagramsection',
            name='instagram_1_image',
            field=models.ImageField(upload_to='instagram/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='instagramsection',
            name='instagram_2_image',
            field=models.ImageField(upload_to='instagram/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='instagramsection',
            name='instagram_3_image',
            field=models.ImageField(upload_to='instagram/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='instagramsection',
            name='instagram_4_image',
            field=models.ImageField(upload_to='instagram/%Y/%m/%d'),
        ),
    ]
