# Generated by Django 4.1.3 on 2022-12-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_item_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item',
            new_name='Order',
        ),
    ]
