# Generated by Django 4.1.3 on 2022-12-23 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_item_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='order',
        ),
    ]
