# Generated by Django 4.1.3 on 2022-12-24 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_item_created_item_modified_order_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['modified']},
        ),
    ]
