# Generated by Django 4.1.3 on 2022-12-24 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_remove_order_address_remove_order_cep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cpf',
        ),
    ]
