# Generated by Django 4.1.3 on 2022-12-24 03:05

from django.db import migrations
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_address_order_cep_order_city_order_complement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=localflavor.br.models.BRStateField(default=1, max_length=2, verbose_name='State'),
            preserve_default=False,
        ),
    ]
