# Generated by Django 4.1.3 on 2022-12-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_item_is_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_sent',
        ),
        migrations.AddField(
            model_name='order',
            name='is_sent',
            field=models.BooleanField(default=False),
        ),
    ]
