# Generated by Django 4.1.3 on 2022-12-24 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_paid',
        ),
    ]
